### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by remram44** [ajl2718/whereabouts#1]
I noticed that the dataset you used ([here](https://data.gov.au/data/dataset/geocoded-national-address-file-g-naf)) has an End-User License Agreement:

> The EULA terms are based on the Creative Commons Attribution 4.0 International license (CC BY 4.0). However, an important restriction relating to the use of the open G-NAF for the sending of mail has been added.
>
> The open G-NAF data must not be used for the generation of an address or the compilation of an address for the sending of mail unless the user has verified that each address to be used for the sending of mail is capable of receiving mail by reference to a secondary source of information. Further information on this use restriction [is available here](https://data.gov.au/dataset/ds-dga-19432f89-dc3a-4ef3-b943-5326ef1dbecc/distribution/dist-dga-9a8f6baa-f790-49a0-84b1-3cb39a6a1b88/details?q=gnaf).

However you claim that your version is MIT with no additional terms. This might not be legal/correct.

**Comment by ajl2718** [comment]
Hi @remram44. Thanks for the clarification and looking into this. I will change the license accordingly.

**Comment by ajl2718** [comment]
Hi @remram44. Thanks again for raising this issue. 

I have updated the README to include a license disclaimer for third-party data and references to these data licenses. The README now mentions specifically that while the code itself is covered by an MIT license it uses data that has other license requirements. This has also now been stated in the huggingface demo page, the huggingface models page and the documentation webpage.

Do you have any other concerns regarding this issue or would you be happy for me to close the issue?

**Comment by ajl2718** [comment]
Reference to third party data and licenses added to README
